export const VOI_JEANS_INVOICE_LIST = "VOI_JEANS_INVOICE_LIST";
export const VOI_JEANS_INVOICE_BY_ID = "VOI_JEANS_INVOICE_BY_ID";
export const VOI_JEANS_INVOICE_PRODUCTLIST_BY_ID =
  "VOI_JEANS_INVOICE_PRODUCTLIST_BY_ID";
export const VOI_JEANS_INVOICE_HSN_CODE = "VOI_JEANS_INVOICE_HSN_CODE";
export const INNOFASHION_INVOICE_LIST = "INNOFASHION_INVOICE_LIST";
export const DEBIT_NOTE_BY_ID = "DEBIT_NOTE_BY_ID";
export const TRANSACTION_BY_ID = "TRANSACTION_BY_ID";
export const INNOFASHION_COUNT = "INNOFASHION_COUNT";
export const VOIJEANS_COUNT = "VOIJEANS_COUNT";
export const INNOFASHION_DATE = "INNOFASHION_DATE";
export const VOIJEANS__AGEING_COUNT = "VOIJEANS__AGEING_COUNT";
